url: "https://www.tudaa.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tudaa" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll/vite
  - jekyll-postcss

postcss:
  cache: false
